<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    use HasFactory;

    protected $primaryKey = 'nisn';
    protected $table = 'siswa';
    protected $casts = ['kode_rombel' => 'string'];
    public $timestamps = true;

    protected $fillable = [
        'nisn',
        'nama_siswa',
        'jenis_kelamin',
        'kelas_id',
        'status_siswa',
        'pas_foto',
        'tempat_lahir',
        'tgl_lahir',
        'agama',
        'alamat',
        'kewarganegaraan',
        'no_tlp',
        'golongan_drh',
        'riwayat_penyakit',
        'kelainan_jasmani',
        'tinggi',
        'berat_bdn',
        'lulusan_dari',
        'tanggal_lulusan',
        'anak_ke',
        'jml_saudara_kandung',
        'jml_saudara_tiri',
        'jml_saudara_angkat',
        'status_anak',
        'tinggal_dng',
        'jarak_kesekolah',
        'nama_ayah_kandung',
        'tgl_lhr_ayah',
        'agama_ayah',
        'kewarganegaraan_ayah',
        'pendidikan_ayah',
        'pekerjaan_ayah',
        'penghasilan_bln_ayah',
        'alamat_ayah',
        'tlp_ayah',
        'nama_ibu_kandung',
        'tgl_lhr_ibu',
        'agama_ibu',
        'kewarganegaraan_ibu',
        'pendidikan_ibu',
        'pekerjaan_ibu',
        'penghasilan_bln_ibu',
        'alamat_ibu',
        'tlp_ibu',
        'nama_wali',
        'tgl_lhr_wali',
        'agama_wali',
        'kewarganegaraan_wali',
        'pendidikan_wali',
        'pekerjaan_wali',
        'penghasilan_bln_wali',
        'alamat_wali',
        'tlp_wali',
    ];

    public static $rules = [
        'nisn' => 'required|unique:siswa,nisn',
        'nama_siswa' => 'required',
        'jenis_kelamin' => 'required',
        'kelas_id' => 'required|exists:kelas,nama_kelas',
        'status_siswa' => 'required',
        'pas_foto' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
        'tempat_lahir' => 'required',
        'tgl_lahir' => 'required|date',
        'agama' => 'required',
        'alamat' => 'required',
        'kewarganegaraan' => 'required',
        'no_tlp' => 'required|unique:siswa,no_tlp',
        'golongan_drh' => 'nullable',
        'riwayat_penyakit' => 'nullable',
        'kelainan_jasmani' => 'nullable',
        'tinggi' => 'required|integer',
        'berat_bdn' => 'required|integer',
        'lulusan_dari' => 'required',
        'tanggal_lulusan' => 'required|date',
        'anak_ke' => 'required|integer',
        'jml_saudara_kandung' => 'nullable|integer',
        'jml_saudara_tiri' => 'nullable|integer',
        'jml_saudara_angkat' => 'nullable|integer',
        'status_anak' => 'required',
        // 'tinggal_dng' => 'required',
        // 'jarak_kesekolah' => 'required|integer',
        'nama_ayah_kandung' => 'required',
        'tgl_lhr_ayah' => 'required|date',
        'agama_ayah' => 'required',
        'kewarganegaraan_ayah' => 'required',
        'pendidikan_ayah' => 'required',
        'pekerjaan_ayah' => 'required',
        'penghasilan_bln_ayah' => 'required|integer',
        'alamat_ayah' => 'required',
        'tlp_ayah' => 'required|unique:siswa,tlp_ayah',
        'nama_ibu_kandung' => 'required',
        'tgl_lhr_ibu' => 'required|date',
        'agama_ibu' => 'required',
        'kewarganegaraan_ibu' => 'required',
        'pendidikan_ibu' => 'required',
        'pekerjaan_ibu' => 'required',
        'penghasilan_bln_ibu' => 'required|integer',
        // 'alamat_ibu' => 'required',
        'tlp_ibu' => 'required|unique:siswa,tlp_ibu',
        'nama_wali' => 'nullable',
        'tgl_lhr_wali' => 'nullable|date',
        'agama_wali' => 'nullable',
        'kewarganegaraan_wali' => 'nullable',
        'pendidikan_wali' => 'nullable',
        'pekerjaan_wali' => 'nullable',
        'penghasilan_bln_wali' => 'nullable|integer',
        'alamat_wali' => 'nullable',
        'tlp_wali' => 'nullable|unique:siswa,tlp_wali',
    ];
    
    public static $messages = [
        'nisn.required' => 'NISN tidak boleh kosong!',
        'nisn.unique' => 'NISN sudah digunakan!',
        'nama_siswa.required' => 'Nama siswa tidak boleh kosong!',
        'jenis_kelamin.required' => 'Jenis kelamin tidak boleh kosong!',
        'kelas_id.required' => 'Kelas tidak boleh kosong!',
        'status_siswa.required' => 'Status siswa tidak boleh kosong!',
        'kelas_id.exists' => 'Kelas yang dipilih tidak valid!',
        'pas_foto.image' => 'Pas foto harus berupa gambar!',
        'pas_foto.mimes' => 'Pas foto harus berupa file dengan format jpeg, png, jpg, atau gif!',
        'pas_foto.max' => 'Pas foto tidak boleh lebih dari 2MB!',
        'tempat_lahir.required' => 'Tempat lahir tidak boleh kosong!',
        'tgl_lahir.required' => 'Tanggal lahir tidak boleh kosong!',
        'tgl_lahir.date' => 'Tanggal lahir harus berupa tanggal yang valid!',
        'agama.required' => 'Agama tidak boleh kosong!',
        'alamat.required' => 'Alamat tidak boleh kosong!',
        'kewarganegaraan.required' => 'Kewarganegaraan tidak boleh kosong!',
        'no_tlp.required' => 'Nomor telepon tidak boleh kosong!',
        'no_tlp.unique' => 'Nomor telepon sudah digunakan!',
        'tinggi.required' => 'Tinggi badan tidak boleh kosong!',
        'tinggi.integer' => 'Tinggi badan harus berupa angka!',
        'berat_bdn.required' => 'Berat badan tidak boleh kosong!',
        'berat_bdn.integer' => 'Berat badan harus berupa angka!',
        'lulusan_dari.required' => 'Asal sekolah tidak boleh kosong!',
        'tanggal_lulusan.required' => 'Tanggal lulus tidak boleh kosong!',
        'tanggal_lulusan.date' => 'Tanggal lulus harus berupa tanggal yang valid!',
        'anak_ke.required' => 'Urutan anak tidak boleh kosong!',
        'anak_ke.integer' => 'Urutan anak harus berupa angka!',
        'status_anak.required' => 'Status anak tidak boleh kosong!',
        // 'tinggal_dng.required' => 'Tempat tinggal dengan siapa tidak boleh kosong!',
        // 'jarak_kesekolah.required' => 'Jarak ke sekolah tidak boleh kosong!',
        // 'jarak_kesekolah.integer' => 'Jarak ke sekolah harus berupa angka!',
        'nama_ayah_kandung.required' => 'Nama ayah kandung tidak boleh kosong!',
        'tgl_lhr_ayah.required' => 'Tanggal lahir ayah tidak boleh kosong!',
        'tgl_lhr_ayah.date' => 'Tanggal lahir ayah harus berupa tanggal yang valid!',
        'agama_ayah.required' => 'Agama ayah tidak boleh kosong!',
        'kewarganegaraan_ayah.required' => 'Kewarganegaraan ayah tidak boleh kosong!',
        'pendidikan_ayah.required' => 'Pendidikan ayah tidak boleh kosong!',
        'pekerjaan_ayah.required' => 'Pekerjaan ayah tidak boleh kosong!',
        'penghasilan_bln_ayah.required' => 'Penghasilan bulanan ayah tidak boleh kosong!',
        'penghasilan_bln_ayah.integer' => 'Penghasilan bulanan ayah harus berupa angka!',
        'alamat_ayah.required' => 'Alamat ayah tidak boleh kosong!',
        'tlp_ayah.required' => 'Nomor telepon ayah tidak boleh kosong!',
        'tlp_ayah.unique' => 'Nomor telepon ayah sudah digunakan!',
        'nama_ibu_kandung.required' => 'Nama ibu kandung tidak boleh kosong!',
        'tgl_lhr_ibu.required' => 'Tanggal lahir ibu tidak boleh kosong!',
        'tgl_lhr_ibu.date' => 'Tanggal lahir ibu harus berupa tanggal yang valid!',
        'agama_ibu.required' => 'Agama ibu tidak boleh kosong!',
        'kewarganegaraan_ibu.required' => 'Kewarganegaraan ibu tidak boleh kosong!',
        'pendidikan_ibu.required' => 'Pendidikan ibu tidak boleh kosong!',
        'pekerjaan_ibu.required' => 'Pekerjaan ibu tidak boleh kosong!',
        'penghasilan_bln_ibu.required' => 'Penghasilan bulanan ibu tidak boleh kosong!',
        'penghasilan_bln_ibu.integer' => 'Penghasilan bulanan ibu harus berupa angka!',
        // 'alamat_ibu.required' => 'Alamat ibu tidak boleh kosong!',
        'tlp_ibu.required' => 'Nomor telepon ibu tidak boleh kosong!',
        'tlp_ibu.unique' => 'Nomor telepon ibu sudah digunakan!',

        'nama_wali.required' => 'Nama Wali kandung tidak boleh kosong!',
        'tgl_lhr_wali.required' => 'Tanggal lahir wali tidak boleh kosong!',
        'tgl_lhr_wali.date' => 'Tanggal lahir wali harus berupa tanggal yang valid!',
        'agama_wali.required' => 'Agama wali tidak boleh kosong!',
        'kewarganegaraan_wali.required' => 'Kewarganegaraan wali tidak boleh kosong!',
        'pendidikan_wali.required' => 'Pendidikan wali tidak boleh kosong!',
        'pekerjaan_wali.required' => 'Pekerjaan wali tidak boleh kosong!',
        'penghasilan_bln_wali.required' => 'Penghasilan bulanan wali tidak boleh kosong!',
        'penghasilan_bln_wali.integer' => 'Penghasilan bulanan wali harus berupa angka!',
        'alamat_wali.required' => 'Alamat wali tidak boleh kosong!',
        'tlp_wali.required' => 'Nomor telepon wali tidak boleh kosong!',
        'tlp_wali.unique' => 'Nomor telepon wali sudah digunakan!',
    ];
}

